#' permutation_solver
#'
#' @description Given a row or column pattern and the set of all possible 
#'     permutations of the row/column's length, `permutation_solver` identifies 
#'     the set of permutations that satisfy the pattern 
#'     
#' @param pattern A numeric vector where ach elmnt corresponds to the length of a run.
#' @param permutation_patterns A matrix of permutations as generated by `make_full_perm_set()`
#'
#' @return
#' @export
#'
#' @examples
permutation_solver <- function(pattern, full_perms) {
  
  full_patterns <- apply(full_perms, 1, function(x){
    pat <- rle(x)$lengths[rle(x)$values==1]
    if(length(pat) == 0) {
      0
    } else pat
  })
  
  matches <- unlist(lapply(full_patterns, function(x) {
    if (length(x) == length(pattern)) {
      all(x == pattern)
    } else
      FALSE
  }))
  
  full_perms[matches, , drop = FALSE]
}